version: '3.1'

services:
  springboot:
    build: .
    # image: registry.gitlab.com/idgst/springboot-mongo-demo:latest
    restart: always
    container_name: inntrade  
    ports:
      - 8080:8080
    working_dir: /opt/app
    depends_on:
      - mongo
  
  mongo:
    image: mongo   
    container_name: inntrade_mongo  
    ports:  # for demo/debug purpose only
      - 27017:27017    
    restart: always